# Generated by Django 2.2.1 on 2019-05-11 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_client', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_pickup', models.DateTimeField(blank=True, null=True)),
                ('detail', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('En Preparación', 'En Preparación'), ('Listo para retirar', 'Listo para retirar'), ('Orden retirada', 'Orden retirada')], default='En Preparación', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
