# Generated by Django 2.2.1 on 2019-05-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_client',
        ),
    ]
